server:
  port: ${SERVER_PORT:8085}

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  # Optional: Logging level for SQL (useful for debugging)
  logging:
    level:
      org:
        springframework:
          jdbc: DEBUG
          hibernate:
            SQL: DEBUG
            type: TRACE
